language: python

python:
  - "3.8.10"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest-cov

script:
  - pytest --cov=.
  - pylint models
  - pylint rest
  - pylint service
  - pylint tests
  - pylint app.py
  - pylint config.py
  - pylint setup.py
  - pylint utils.py
  - pylint wsgi.py

after_success:
  - coveralls