language: python

python:
  - "3.8.10"

install:
  - pip install -r requirements.txt

script:
  - python -m pytest -v tests/test_login.py
  - python -m pytest -v tests/test_match.py
  - python -m pytest -v tests/test_prediction.py
  - python -m pytest -v tests/test_team.py
  - python -m pytest -v tests/test_user.py

after_success:
  - coveralls