language: python

python:
  - "3.8.10"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest-cov

script: pytest --cov=rest --cov-append=service

after_success:
  - coveralls