language: python

python:
  - "3.8.10"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest-cov

script:
  - pytest --cov=.
  - python -m pylint --load-plugins pylint_flask_sqlalchemy models
  - python -m pylint --load-plugins pylint_flask_sqlalchemy rest
  - python -m pylint --load-plugins pylint_flask_sqlalchemy service
  - python -m pylint --load-plugins pylint_flask_sqlalchemy tests
  - python -m pylint --load-plugins pylint_flask_sqlalchemy app.py
  - python -m pylint --load-plugins pylint_flask_sqlalchemy config.py
  - python -m pylint --load-plugins pylint_flask_sqlalchemy utils.py

after_success:
  - coveralls