"""Initial migration.

Revision ID: 14838829462d
Revises: 12d63d06710a
Create Date: 2021-12-28 11:37:09.403820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14838829462d'
down_revision = '12d63d06710a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id_'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id_'], ),
    sa.PrimaryKeyConstraint('team_id', 'match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
