"""Initial migration.

Revision ID: f0375dd4be94
Revises: 1f2d14d71932
Create Date: 2021-12-27 21:26:36.892207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0375dd4be94'
down_revision = '1f2d14d71932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('model', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    # ### end Alembic commands ###
