"""Initial migration.

Revision ID: f723bdd65008
Revises: f0375dd4be94
Create Date: 2021-12-27 21:45:51.110853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f723bdd65008'
down_revision = 'f0375dd4be94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id_', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id_'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
